export const FETCH_METADATA = 'FETCH_METADATA';
export const METADATA_FETCHED = 'METADATA_FETCHED';
export const FETCH_ENTITIES = 'FETCH_ENTITIES';
export const ENTITIES_FETCHED = 'ENTITIES_FETCHED';
